### ISSUE TITLE
Add this plugin to the awesome-list?

### ISSUE THREAD

**Issue by 0xnoob** [bet4it/hyperinator#1]
Hi,

First of all, **thank you!** 
Now it's so much easier to switch from tmux to hyperlayout!

Maybe add it to [/bnb/awesome-hyper/](/bnb/awesome-hyper/) - so others can find it easier?  
I was thinking about opening an issue there myself, but asking here first seemed appropriate.

**Comment by bet4it** [comment]
Refer: bnb/awesome-hyper#363

**Comment by 0xnoob** [comment]
Welp, may bad - should have checked there before!
