### ISSUE TITLE
How to determine correct panes sizes?

### ISSUE THREAD

**Issue by jbalzar** [bet4it/hyperinator#4]
Hello @bet4it, Great plugin! It works on my Windows 10 using PowerShell 7. 

I have question about the panes sizing. 

For this simple config:

```
windows:
- layout: 5162,237x48,0,0{118x48,0,0,152,118x48,119,0,153}
  panes:
  - echo 'First pane'
  - echo 'Second pane'
```

I'm trying to figure out how to set the size of the 'Second pane'. I don't have experience using tmuxinator. Can you explain each segment here?

```- layout: 5162,237x48,0,0{118x48,0,0,152,118x48,119,0,153}```

Thanks!

**Comment by bet4it** [comment]
I can explain it, but it's not suitable to change manually.
The best way is using `tmux` to generate it. (You don't need `tmuxinator`)

**Comment by jbalzar** [comment]
Ok, got it! Thanks 👍
