### ISSUE TITLE
updating plugins error

### ISSUE THREAD

**Issue by TensorPlus** [bet4it/hyperinator#5]
![搜狗截图21年04月09日2051_3](https://user-images.githubusercontent.com/51601224/114182557-5585fd80-9975-11eb-9e66-9ca43aebe4c1.png)
我能正常访问raw.githubusercontent.com，配置 /etc/hosts 也试过了，但是还是 updating plugins error
![搜狗截图21年04月09日2047_2](https://user-images.githubusercontent.com/51601224/114182389-23749b80-9975-11eb-9647-b3a9f9fd3809.png)

**Comment by bet4it** [comment]
What about now?
